baseURL = 'https://vhdlverilog.com/'
languageCode = 'tr-tr'
title = 'VHDLVerilog'
theme = 'pehtheme-hugo'
buildFuture = true

paginate = '6' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = '' # <- Your GA-4
disqusShortname = '' # <- Get form here : https://disqus.com

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'vhdlverilog.com'
	mainSections = 'posts'

[author]
	name = 'Seçkin Albamya'
	bio = 'FPGA ve gömülü sistemler ve insansız hava araçları üzerine çalışma yapan elektronik meraklısı'
	avatar = '/images/seckin_pp.jpg'

[menu] # Menu management
	[[menu.main]]
		name = 'Ana Sayfa'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'Hakkında'
		pageRef = '/hakkinda'
		weight = 15

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'
